apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: hellonode
  name: hellonode
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hellonode
  template:
    metadata:
      labels:
        name: hellonode
    spec:
      containers:
      - name: hellonode
        image: registry.eu-west-0.prod-cloud-ocb.orange-business.com/dafurepo/hellonode:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: default-secret
      restartPolicy: Always
