apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    cce/appgroup: hellonode
    name: hellonode
  name: hellonode
  namespace: default
spec:
  replicas: 2
  selector:
    cce/appgroup: hellonode
    name: hellonode
  template:
    metadata:
      labels:
        cce/appgroup: hellonode
        name: hellonode
    spec:
      containers:
      - name: hellonode
        image: 100.125.0.94:20202/dafurepo/hellonode:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregistry
      restartPolicy: Always
