apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    cce/appgroup: hellonode
    name: hellonode
  name: hellonode
  namespace: default
spec:
  replicas: 1
  selector:
    cce/appgroup: hellonode
    name: hellonode
  template:
    metadata:
      labels:
        cce/appgroup: hellonode
        name: hellonode
    spec:
      containers:
      - env:
        image: 100.125.0.24:6443/ocb0001686/hellonode:latest
        imagePullPolicy: Always
        name: hellonode
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: myregistry
      restartPolicy: Always
