apiVersion: v1
kind: Service
metadata:
  labels:
    name: hellonode
  name: hellonode
  namespace: default
spec:
  ports:
  - name: hellonode
    nodePort: 30008
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    name: hellonode
  type: NodePort
