apiVersion: v1
kind: Service
metadata:
  labels:
    cce/appgroup: hellonode
    name: hellonode
  name: hellonode
  namespace: default
spec:
  ports:
  - name: hellonode
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    cce/appgroup: hellonode
    name: hellonode
  type: NodePort
